import {
  CURRENT_ENTERPRISE_NAME,
  Order,
  Reservation,
  ReservationSlot
} from './reservation-workspace.models';

export const MOCK_SLOTS: ReservationSlot[] = [
  {
    id: 'SLT-201',
    name: 'Rades Dock 2',
    zone: 'Rades Port Zone',
    city: 'Ben Arous',
    ownerCompany: CURRENT_ENTERPRISE_NAME,
    portfolio: 'owned',
    type: 'Dock',
    coordinates: [36.7687, 10.2759],
    capacity: 16,
    occupied: 12,
    status: 'peak',
    equipment: ['RFID gate', 'Cold chain', 'Truck ramp'],
    images: [],
    heatmap: [
      [70, 76, 82, 90, 88, 80, 66],
      [64, 69, 74, 86, 83, 71, 58],
      [58, 62, 70, 80, 76, 63, 51],
      [61, 66, 74, 84, 79, 67, 55],
      [74, 79, 86, 94, 91, 84, 71],
      [45, 50, 56, 62, 58, 52, 40],
      [34, 39, 46, 52, 48, 42, 31]
    ],
    forecast: [87, 90, 85, 83, 88, 79, 74],
    utilizationRate: 0,
    predictedAvailability: 0,
    underusedScore: 0,
    recoveryAction: ''
  },
  {
    id: 'SLT-202',
    name: 'Mghira South Warehouse',
    zone: 'Mghira Industrial Zone',
    city: 'Ben Arous',
    ownerCompany: CURRENT_ENTERPRISE_NAME,
    portfolio: 'owned',
    type: 'Storage',
    coordinates: [36.7189, 10.2243],
    capacity: 26,
    occupied: 9,
    status: 'available',
    equipment: ['Smart shelving', 'Barcode tunnel', 'Dry zone'],
    images: [],
    heatmap: [
      [28, 31, 34, 39, 42, 37, 29],
      [24, 28, 30, 35, 38, 33, 26],
      [20, 24, 28, 31, 34, 29, 22],
      [24, 29, 32, 36, 39, 33, 26],
      [29, 33, 36, 42, 45, 39, 31],
      [17, 21, 24, 28, 30, 24, 18],
      [14, 17, 20, 23, 26, 21, 16]
    ],
    forecast: [43, 41, 39, 42, 45, 40, 36],
    utilizationRate: 0,
    predictedAvailability: 0,
    underusedScore: 0,
    recoveryAction: ''
  },
  {
    id: 'SLT-203',
    name: 'Lac 1 Meeting Lounge',
    zone: 'Les Berges du Lac',
    city: 'Tunis',
    ownerCompany: 'Carthage Packaging',
    portfolio: 'partner',
    type: 'Meeting',
    coordinates: [36.8447, 10.2824],
    capacity: 12,
    occupied: 6,
    status: 'balanced',
    equipment: ['Video conference suite', 'Wall display', 'Phone booths'],
    images: [],
    heatmap: [
      [39, 50, 62, 67, 60, 43, 21],
      [33, 46, 58, 63, 56, 39, 17],
      [36, 48, 57, 61, 54, 38, 19],
      [40, 52, 63, 68, 61, 44, 22],
      [45, 57, 68, 73, 65, 48, 27],
      [20, 25, 30, 34, 27, 18, 12],
      [15, 19, 23, 26, 20, 13, 10]
    ],
    forecast: [57, 59, 61, 60, 63, 51, 43],
    utilizationRate: 0,
    predictedAvailability: 0,
    underusedScore: 0,
    recoveryAction: ''
  },
  {
    id: 'SLT-204',
    name: 'Sousse Line 3 Workshop',
    zone: 'Sousse Industrial Zone',
    city: 'Sousse',
    ownerCompany: 'Sousse Metal Services',
    portfolio: 'partner',
    type: 'Production',
    coordinates: [35.8361, 10.6258],
    capacity: 18,
    occupied: 14,
    status: 'maintenance',
    equipment: ['Energy sensors', 'Material scanner', 'Quality bridge'],
    images: [],
    heatmap: [
      [76, 82, 87, 89, 86, 80, 66],
      [72, 77, 82, 86, 83, 77, 61],
      [69, 73, 79, 83, 80, 73, 56],
      [67, 72, 78, 82, 79, 73, 55],
      [80, 84, 89, 93, 89, 84, 69],
      [43, 48, 54, 57, 53, 47, 36],
      [29, 33, 38, 41, 37, 31, 24]
    ],
    forecast: [91, 88, 86, 85, 87, 77, 69],
    utilizationRate: 0,
    predictedAvailability: 0,
    underusedScore: 0,
    recoveryAction: ''
  },
  {
    id: 'SLT-205',
    name: 'Sfax Poudriere Hub',
    zone: 'Route de la Poudriere',
    city: 'Sfax',
    ownerCompany: CURRENT_ENTERPRISE_NAME,
    portfolio: 'owned',
    type: 'Production',
    coordinates: [34.7684, 10.7605],
    capacity: 20,
    occupied: 13,
    status: 'balanced',
    equipment: ['Optical sorting', 'Fast weighing', 'Export pallet zone'],
    images: [],
    heatmap: [
      [49, 56, 64, 68, 63, 52, 34],
      [44, 50, 59, 64, 59, 47, 30],
      [42, 49, 57, 62, 56, 45, 28],
      [46, 53, 61, 66, 61, 49, 32],
      [52, 59, 67, 72, 66, 54, 36],
      [25, 31, 36, 40, 34, 25, 17],
      [18, 23, 27, 30, 24, 17, 11]
    ],
    forecast: [64, 66, 63, 61, 65, 55, 48],
    utilizationRate: 0,
    predictedAvailability: 0,
    underusedScore: 0,
    recoveryAction: ''
  }
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'RES-401',
    code: 'RSV-401',
    title: 'PET pallet loading',
    customer: 'El Amen Recycling',
    resource: 'Logistics dock 2',
    slotId: 'SLT-201',
    slotName: '',
    role: 'provider',
    city: 'Ben Arous',
    category: 'Space',
    providerCompany: CURRENT_ENTERPRISE_NAME,
    consumerCompany: 'El Amen Recycling',
    start: '2026-05-08T09:00',
    end: '2026-05-08T12:00',
    headcount: 8,
    amount: 4600,
    status: 'risk',
    notes: 'The client expects a quick truck turn with exit paperwork and customs validation before noon.',
    tags: ['Export', 'Customs', 'Priority'],
    contactName: 'Hatem Jlassi',
    contactEmail: 'hatem.jlassi@elamen.tn',
    contactPhone: '+216 98 112 334',
    notificationChannel: 'both',
    confirmationNotice: null,
    color: '#0ea5e9',
    cancellationRisk: 0,
    recommendedTime: '',
    bookingSuggestion: ''
  },
  {
    id: 'RES-402',
    code: 'RSV-402',
    title: 'Reusable packaging review',
    customer: 'Carthage Packaging',
    resource: 'Client review lounge',
    slotId: 'SLT-203',
    slotName: '',
    role: 'consumer',
    city: 'Tunis',
    category: 'Space',
    providerCompany: 'Carthage Packaging',
    consumerCompany: CURRENT_ENTERPRISE_NAME,
    start: '2026-05-09T10:00',
    end: '2026-05-09T12:30',
    headcount: 6,
    amount: 1850,
    status: 'confirmed',
    notes: 'Planning session for a joint offer around reusable packaging flows.',
    tags: ['Partnership', 'Client', 'Lake'],
    contactName: 'Meriem Kacem',
    contactEmail: 'meriem.kacem@carthagepack.tn',
    contactPhone: '+216 55 240 118',
    notificationChannel: 'email',
    confirmationNotice: null,
    color: '#38bdf8',
    cancellationRisk: 0,
    recommendedTime: '',
    bookingSuggestion: ''
  },
  {
    id: 'RES-403',
    code: 'RSV-403',
    title: 'Finished leather storage',
    customer: 'Maison du Cuir Sahel',
    resource: 'Buffer warehouse B',
    slotId: 'SLT-202',
    slotName: '',
    role: 'provider',
    city: 'Ben Arous',
    category: 'Storage',
    providerCompany: CURRENT_ENTERPRISE_NAME,
    consumerCompany: 'Maison du Cuir Sahel',
    start: '2026-05-10T08:00',
    end: '2026-05-10T16:00',
    headcount: 4,
    amount: 2400,
    status: 'confirmed',
    notes: 'Short-term storage before transfer toward La Goulette port.',
    tags: ['Storage', 'Transit'],
    contactName: 'Alaa Siala',
    contactEmail: 'alaa.siala@cuirsahel.tn',
    contactPhone: '+216 24 781 225',
    notificationChannel: 'sms',
    confirmationNotice: null,
    color: '#22c55e',
    cancellationRisk: 0,
    recommendedTime: '',
    bookingSuggestion: ''
  },
  {
    id: 'RES-404',
    code: 'RSV-404',
    title: 'Circular steel cutting',
    customer: 'Sousse Metal Services',
    resource: 'Cutting line 3',
    slotId: 'SLT-204',
    slotName: '',
    role: 'consumer',
    city: 'Sousse',
    category: 'Production',
    providerCompany: 'Sousse Metal Services',
    consumerCompany: CURRENT_ENTERPRISE_NAME,
    start: '2026-05-11T14:00',
    end: '2026-05-11T17:00',
    headcount: 9,
    amount: 5200,
    status: 'pending',
    notes: 'Pilot batch mission with same-evening quality approval expected.',
    tags: ['Metal', 'Pilot', 'Quality'],
    contactName: 'Saber Ben Romdhane',
    contactEmail: 'saber@smetal.tn',
    contactPhone: '+216 29 600 441',
    notificationChannel: 'email',
    confirmationNotice: null,
    color: '#0f766e',
    cancellationRisk: 0,
    recommendedTime: '',
    bookingSuggestion: ''
  },
  {
    id: 'RES-405',
    code: 'RSV-405',
    title: 'High-volume carton sorting',
    customer: 'Central Carton Office',
    resource: 'South sorting cell',
    slotId: 'SLT-205',
    slotName: '',
    role: 'provider',
    city: 'Sfax',
    category: 'Production',
    providerCompany: CURRENT_ENTERPRISE_NAME,
    consumerCompany: 'Central Carton Office',
    start: '2026-05-12T08:30',
    end: '2026-05-12T13:30',
    headcount: 11,
    amount: 3900,
    status: 'confirmed',
    notes: 'Heavy run planned to smooth production before a transfer toward Kairouan.',
    tags: ['Output', 'Sfax'],
    contactName: 'Wafa Ben Abdallah',
    contactEmail: 'wafa@cartoncentre.tn',
    contactPhone: '+216 21 908 664',
    notificationChannel: 'both',
    confirmationNotice: null,
    color: '#0284c7',
    cancellationRisk: 0,
    recommendedTime: '',
    bookingSuggestion: ''
  },
  {
    id: 'RES-406',
    code: 'RSV-406',
    title: 'Agri-export dock passage',
    customer: 'Bizerte Agro Export',
    resource: 'Logistics dock 2',
    slotId: 'SLT-201',
    slotName: '',
    role: 'provider',
    city: 'Ben Arous',
    category: 'Space',
    providerCompany: CURRENT_ENTERPRISE_NAME,
    consumerCompany: 'Bizerte Agro Export',
    start: '2026-05-08T11:30',
    end: '2026-05-08T14:30',
    headcount: 7,
    amount: 4100,
    status: 'risk',
    notes: 'Tight window with temperature control and proof of loading required before departure.',
    tags: ['Agri', 'Temperature', 'Proof'],
    contactName: 'Riadh Mhiri',
    contactEmail: 'riadh@bizerteagro.tn',
    contactPhone: '+216 27 540 223',
    notificationChannel: 'sms',
    confirmationNotice: null,
    color: '#7dd3fc',
    cancellationRisk: 0,
    recommendedTime: '',
    bookingSuggestion: ''
  },
  {
    id: 'RES-407',
    code: 'RSV-407',
    title: 'Packaging sector presentation',
    customer: 'Carthage Packaging',
    resource: 'Signature room',
    slotId: 'SLT-203',
    slotName: '',
    role: 'consumer',
    city: 'Tunis',
    category: 'Space',
    providerCompany: 'Carthage Packaging',
    consumerCompany: CURRENT_ENTERPRISE_NAME,
    start: '2026-05-13T15:00',
    end: '2026-05-13T17:00',
    headcount: 5,
    amount: 1650,
    status: 'pending',
    notes: 'Presentation session with a regional delegation and sample finalization.',
    tags: ['Presentation', 'Tunis'],
    contactName: 'Nesrine Chaari',
    contactEmail: 'nesrine.chaari@carthagepack.tn',
    contactPhone: '+216 20 114 907',
    notificationChannel: 'email',
    confirmationNotice: null,
    color: '#38bdf8',
    cancellationRisk: 0,
    recommendedTime: '',
    bookingSuggestion: ''
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-901',
    code: 'OR-901',
    invoiceNumber: 'INV-901',
    customer: 'El Amen Recycling',
    reservationId: 'RES-401',
    slotId: 'SLT-201',
    role: 'provider',
    city: 'Ben Arous',
    buyerCompany: 'El Amen Recycling',
    sellerCompany: CURRENT_ENTERPRISE_NAME,
    amount: 4600,
    tax: 874,
    total: 5474,
    createdAt: '2026-05-04',
    dueDate: '2026-05-12',
    status: 'processing',
    paymentStatus: 'review',
    items: [
      { label: 'Main dock access', quantity: 1, unitPrice: 3100 },
      { label: 'Document handling', quantity: 1, unitPrice: 900 },
      { label: 'Loading crew', quantity: 1, unitPrice: 600 }
    ],
    qrValue: 'eco://orders/ORD-901',
    tracking: [],
    fraudRisk: 0,
    spendingCluster: '',
    paymentInsight: ''
  },
  {
    id: 'ORD-902',
    code: 'OR-902',
    invoiceNumber: 'INV-902',
    customer: 'Carthage Packaging',
    reservationId: 'RES-402',
    slotId: 'SLT-203',
    role: 'consumer',
    city: 'Tunis',
    buyerCompany: CURRENT_ENTERPRISE_NAME,
    sellerCompany: 'Carthage Packaging',
    amount: 1850,
    tax: 351.5,
    total: 2201.5,
    createdAt: '2026-05-03',
    dueDate: '2026-05-10',
    status: 'invoiced',
    paymentStatus: 'pending',
    items: [
      { label: 'Meeting lounge access', quantity: 1, unitPrice: 1320 },
      { label: 'Partner welcome pack', quantity: 1, unitPrice: 530 }
    ],
    qrValue: 'eco://orders/ORD-902',
    tracking: [],
    fraudRisk: 0,
    spendingCluster: '',
    paymentInsight: ''
  },
  {
    id: 'ORD-903',
    code: 'OR-903',
    invoiceNumber: 'INV-903',
    customer: 'Maison du Cuir Sahel',
    reservationId: 'RES-403',
    slotId: 'SLT-202',
    role: 'provider',
    city: 'Ben Arous',
    buyerCompany: 'Maison du Cuir Sahel',
    sellerCompany: CURRENT_ENTERPRISE_NAME,
    amount: 2400,
    tax: 456,
    total: 2856,
    createdAt: '2026-05-02',
    dueDate: '2026-05-14',
    status: 'fulfilled',
    paymentStatus: 'paid',
    items: [
      { label: 'Temporary storage', quantity: 2, unitPrice: 860 },
      { label: 'Weekend handling', quantity: 1, unitPrice: 680 }
    ],
    qrValue: 'eco://orders/ORD-903',
    tracking: [],
    fraudRisk: 0,
    spendingCluster: '',
    paymentInsight: ''
  },
  {
    id: 'ORD-904',
    code: 'OR-904',
    invoiceNumber: 'INV-904',
    customer: 'Sousse Metal Services',
    reservationId: 'RES-404',
    slotId: 'SLT-204',
    role: 'consumer',
    city: 'Sousse',
    buyerCompany: CURRENT_ENTERPRISE_NAME,
    sellerCompany: 'Sousse Metal Services',
    amount: 5200,
    tax: 988,
    total: 6188,
    createdAt: '2026-05-05',
    dueDate: '2026-05-16',
    status: 'draft',
    paymentStatus: 'review',
    items: [
      { label: 'Line 3 machine time', quantity: 1, unitPrice: 3800 },
      { label: 'Extended quality control', quantity: 1, unitPrice: 900 },
      { label: 'Urgent slot', quantity: 1, unitPrice: 500 }
    ],
    qrValue: 'eco://orders/ORD-904',
    tracking: [],
    fraudRisk: 0,
    spendingCluster: '',
    paymentInsight: ''
  },
  {
    id: 'ORD-905',
    code: 'OR-905',
    invoiceNumber: 'INV-905',
    customer: 'Central Carton Office',
    reservationId: 'RES-405',
    slotId: 'SLT-205',
    role: 'provider',
    city: 'Sfax',
    buyerCompany: 'Central Carton Office',
    sellerCompany: CURRENT_ENTERPRISE_NAME,
    amount: 3900,
    tax: 741,
    total: 4641,
    createdAt: '2026-05-04',
    dueDate: '2026-05-13',
    status: 'invoiced',
    paymentStatus: 'pending',
    items: [
      { label: 'South sorting capacity', quantity: 1, unitPrice: 2850 },
      { label: 'Midday output review', quantity: 1, unitPrice: 650 },
      { label: 'Pallet preparation', quantity: 1, unitPrice: 400 }
    ],
    qrValue: 'eco://orders/ORD-905',
    tracking: [],
    fraudRisk: 0,
    spendingCluster: '',
    paymentInsight: ''
  },
  {
    id: 'ORD-906',
    code: 'OR-906',
    invoiceNumber: 'INV-906',
    customer: 'Bizerte Agro Export',
    reservationId: 'RES-406',
    slotId: 'SLT-201',
    role: 'provider',
    city: 'Ben Arous',
    buyerCompany: 'Bizerte Agro Export',
    sellerCompany: CURRENT_ENTERPRISE_NAME,
    amount: 4100,
    tax: 779,
    total: 4879,
    createdAt: '2026-05-05',
    dueDate: '2026-05-15',
    status: 'processing',
    paymentStatus: 'pending',
    items: [
      { label: 'Priority dock access', quantity: 1, unitPrice: 2800 },
      { label: 'Temperature follow-up', quantity: 1, unitPrice: 850 },
      { label: 'Loading proof', quantity: 1, unitPrice: 450 }
    ],
    qrValue: 'eco://orders/ORD-906',
    tracking: [],
    fraudRisk: 0,
    spendingCluster: '',
    paymentInsight: ''
  }
];
